/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#1A2744",
        "primary-dark": "#E5E5E5",
        teal: "#1D9E75",
        "teal-dark": "#3DD6A3",
        violet: "#534AB7",
        "violet-dark": "#A594F9",
        surface: "#FFFFFF",
        "surface-dark": "#0F0F0F",
        "surface-alt": "#F1F3F7",
        "surface-alt-dark": "#171717",
        navy: "#0D1321",
        "navy-dark": "#FAFAFA",
        background: "#F7F8FA",
        "background-dark": "#000000",
        error: "#E24B4A",
        "error-dark": "#F87171",
        success: "#1D9E75",
        "success-dark": "#3DD6A3",
        warning: "#BA7517",
        "warning-dark": "#FBBF24",
        muted: "#A0AABA",
        "muted-dark": "#525252",
        "app-border": "#E8ECF2",
        "app-border-dark": "#262626",
      },
      fontFamily: {
        sans: ["Inter_400Regular"],
        medium: ["Inter_500Medium"],
        semibold: ["Inter_600SemiBold"],
        bold: ["Inter_700Bold"],
        extrabold: ["Inter_800ExtraBold"],
      },
      fontSize: {
        "body": ["17px", { lineHeight: "24px" }],
        "body-lg": ["20px", { lineHeight: "28px" }],
        "heading": ["24px", { lineHeight: "32px" }],
        "heading-lg": ["28px", { lineHeight: "36px" }],
        "display": ["34px", { lineHeight: "42px" }],
      },
      minHeight: {
        "touch": "56px",
        "touch-lg": "64px",
      },
      minWidth: {
        "touch": "56px",
      },
      borderRadius: {
        "xl": "12px",
        "2xl": "16px",
        "3xl": "20px",
      },
    },
  },
  plugins: [],
};
